---
Title: 20200123 Exercises
output: pdf_document
---
# 20200123 Exercises

## Liam Godin

# Page 2 exercise 1

	int theRightInteger(int i1, double d1, int* iP) {
		int result = 0;
		// The rest of the function body
		return result;
	}

# Page 2 exercise 2

	Room* getNextRoom(LLNode* listP) {
		Room* pointer = 0;
		// The rest of the function body
		return pointer;
	}

# Page 3 exercise 3

	LLNode* checkList (LLNode* node, Room* roomP) {
		LLNode* result = 0;
		// The rest of the function body
		return result;
	}

# Page 3 exercise 1

* Regular date to test
* Ending points of year (Jan 1, Dec 31)
* Leap Year
* Day that doesn't exist (Feb 31)
* Impossible Date (Dec 40)
* 9 day stretch

# Page 4 exercise 2

* Cell dying
* Cell coming back to life
* Cell staying dead
* Cells dying due to cells coming back to life

# Page 5 exercise 1

* Simple division
* Complex division
* Division by 0
* Division of 0
* Division 0/0
* Division of negatives

# Page 5 exercise 2 

* Test all products (use absolute max price)
* Test no products (use $0)
* test invalid product
* communication issues
* filter for current location

# Page 5 exercise 3

* Prototype goes in tests.h
* implementation goes in tests.c
* test suit invoked in main.c
* individual tests invoked in tests.c
